language: php

php:
  - 7.0
  - 7.1
  - 7.2
  
before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --verbose --ignore-platform-reqs"

script:
  - "vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover"
